nosana:
  description: Run Test 2


global:
  image: registry.hub.docker.com/library/node:16
  trigger:
    branch:
      - all

jobs:
  - name: install-deps and run test
    commands:
      - sh -c 'echo secret is $SECRET'
      - npm ci
      - npm run test
